name: Test `install.sh`

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run environment setup script
        run: |
          chmod +x ./scripts/install.sh
          ./scripts/install.sh -n dummy -e dummy@example.com

      - name: Verify `bat` command is available
        run: |
          if ! command -v bat &> /dev/null
          then
            echo "Command 'bat' not found, test failed!"
            exit 1
          fi
          echo "Command 'bat' is available, test passed!"

      - name: Verify `brew` command is available
        run: |
          if ! command -v brew &> /dev/null
          then
            echo "Command 'brew' not found, test failed!"
            exit 1
          fi
          echo "Command 'brew' is available, test passed!"

      - name: Verify `ffmpeg` command is available
        run: |
          if ! command -v ffmpeg &> /dev/null
          then
            echo "Command 'ffmpeg' not found, test failed!"
            exit 1
          fi
          echo "Command 'ffmpeg' is available, test passed!"

      - name: Verify `fish` command is available
        run: |
          if ! command -v fish &> /dev/null
          then
            echo "Command 'fish' not found, test failed!"
            exit 1
          fi
          echo "Command 'fish' is available, test passed!"

      - name: Verify `fzf` command is available
        run: |
          if ! command -v fzf &> /dev/null
          then
            echo "Command 'fzf' not found, test failed!"
            exit 1
          fi
          echo "Command 'fzf' is available, test passed!"

      - name: Verify `git` command is available
        run: |
          if ! command -v git &> /dev/null
          then
            echo "Command 'git' not found, test failed!"
            exit 1
          fi
          echo "Command 'git' is available, test passed!"

      - name: Verify `lsd` command is available
        run: |
          if ! command -v lsd &> /dev/null
          then
            echo "Command 'lsd' not found, test failed!"
            exit 1
          fi
          echo "Command 'lsd' is available, test passed!"

      - name: Verify `mise` command is available
        run: |
          if ! command -v mise &> /dev/null
          then
            echo "Command 'mise' not found, test failed!"
            exit 1
          fi
          echo "Command 'mise' is available, test passed!"

      - name: Verify `nvim` command is available
        run: |
          if ! command -v nvim &> /dev/null
          then
            echo "Command 'nvim' not found, test failed!"
            exit 1
          fi
          echo "Command 'nvim' is available, test passed!"

      - name: Verify `node` command is available
        run: |
          if ! command -v node &> /dev/null
          then
            echo "Command 'node' not found, test failed!"
            exit 1
          fi
          echo "Command 'node' is available, test passed!"

      - name: Verify `python3` command is available
        run: |
          if ! command -v python3 &> /dev/null
          then
            echo "Command 'python3' not found, test failed!"
            exit 1
          fi
          echo "Command 'python3' is available, test passed!"

      - name: Verify `rg` command is available
        run: |
          if ! command -v rg &> /dev/null
          then
            echo "Command 'rg' not found, test failed!"
            exit 1
          fi
          echo "Command 'rg' is available, test passed!"

      - name: Verify `starship` command is available
        run: |
          if ! command -v starship &> /dev/null
          then
            echo "Command 'starship' not found, test failed!"
            exit 1
          fi
          echo "Command 'starship' is available, test passed!"

      - name: Verify `zoxide` command is available
        run: |
          if ! command -v zoxide &> /dev/null
          then
            echo "Command 'zoxide' not found, test failed!"
            exit 1
          fi
          echo "Command 'zoxide' is available, test passed!"

      - name: Check if `.Brewfile` exists
        run: |
          if find "$HOME" -name ".Brewfile"; then
            echo "The file found, test passed!"
          else
            echo "The file not found, test failed!"
            exit 1
          fi

      - name: Check if `alacritty.toml` exists
        run: |
          if find "$HOME/.config/alacritty" -name "alacritty.toml"; then
            echo "The file found, test passed!"
          else
            echo "The file not found, test failed!"
            exit 1
          fi

      - name: Check if `starship.toml` exists
        run: |
          if find "$HOME/.config" -name "starship.toml"; then
            echo "The file found, test passed!"
          else
            echo "The file not found, test failed!"
            exit 1
          fi
      
      - name: Should Git username is configured
        run: |
          if [ "$(git config --global user.name)" != "dummy" ]; then
            echo "user.name is not set correctly"
            exit 1
          fi
      
      - name: Should Git user email is configured
        run: |
          if [ "$(git config --global user.email)" != "dummy@example.com" ]; then
            echo "user.email is not set correctly"
            exit 1
          fi
