name: Test `install.sh`

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }} 

    env:
      GOSS_USE_ALPHA: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run environment setup script
        run: |
          chmod +x ./scripts/install.sh
          ./scripts/install.sh -n dummy -e dummy@example.com

      - name: Testing by Goss (MacOS)
        if: runner.os == 'macOS'
        run: |
          curl -L https://github.com/goss-org/goss/releases/download/v0.4.9/goss-darwin-arm64 -o goss
          chmod +x goss
          ./goss validate -f documentation

      - name: Testing by Goss (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          bat /etc/shells
          sed -i 's|/opt/homebrew/bin/fish|/usr/bin/fish|' goss.yaml
          curl -L https://github.com/goss-org/goss/releases/download/v0.4.9/goss-linux-amd64 -o goss
          chmod +x goss
          ./goss validate -f documentation

