name: Test Git Config on Windows

on:
  push:
    branches:
      - main  # テストを実行するブランチを指定
  pull_request:
    branches:
      - main  # プルリクエスト時にもテストを実行

jobs:
  test-git-config-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git user and email
        run: |
          ./configs/install.ps1 -n "dummy" -e "dummy@example.com"
        shell: pwsh

      - name: Verify Git user.name
        run: |
          if [ "$(git config --global user.name)" != "dummy" ]; then
            echo "Expected Git user.name to be 'dummy', but found '$(git config --global user.name)'"
            exit 1
          fi
        shell: bash

      - name: Verify Git user.email
        run: |
          if [ "$(git config --global user.email)" != "dummy@example.com" ]; then
            echo "Expected Git user.email to be 'dummy@example.com', but found '$(git config --global user.email)'"
            exit 1
          fi
        shell: bash

      - name: Output success message
        run: echo "Git user.name and user.email are correctly set."
        shell: bash
