name: Test `install.ps1`

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run environment setup script
        run: ./scripts/install.ps1 -n "dummy" -e "dummy@example.com"
        shell: pwsh

      - name: Should `choco` comamnd is available
        shell: pwsh
        run: |
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
            Write-Error "Chocolatey (choco) is not installed."
            exit 1
          }

      - name: Should Git username configured
        run: |
          if [ "$(git config --global user.name)" != "dummy" ]; then
            echo "Expected Git user.name to be 'dummy', but found '$(git config --global user.name)'"
            exit 1
          fi
        shell: bash

      - name: Should Git user email configured
        run: |
          if [ "$(git config --global user.email)" != "dummy@example.com" ]; then
            echo "Expected Git user.email to be 'dummy@example.com', but found '$(git config --global user.email)'"
            exit 1
          fi
        shell: bash

